### ISSUE TITLE
Windows github action总是通不过

### ISSUE THREAD

**Issue by zjhellofss** [zjhellofss/KuiperInfer#18]
@Azusachan 失败记录在Actions中，不清楚是代码问题还是配置问题。另外windows action ci时间过长，有没有好的解决办法

**Comment by Azusachan** [comment]
失败的问题是 openmp的simd 需要/llvm:experiemental，https://github.com/dotnet/msbuild/issues/6702
时间过长是因为缓存没有保存vcpkg的包，导致每次ci都要重新编译所有依赖
