### ISSUE TITLE
可以尝试直接使用 MegCC 来生成具体每个 op 的 kernel C 代码

### ISSUE THREAD

**Issue by chenqy4933** [zjhellofss/KuiperInfer#2]
[MegCC](https://github.com/MegEngine/MegCC) 最近会支持一个命令行工具，输入需要生成的Op的类型，参数，直接吐出来具体的 Kernel。欢迎试用。。。。

**Comment by znsoftm** [comment]
支持直接读取pytorch或onnx模型不？ onnx转 mengine不灵，好多转换不了（当然，你可以说是算子不支持）

**Comment by chenqy4933** [comment]
暂时没有支持支持，目前的方法确实只能通过 mgeconvert 来转，短期内暂时没有人力支持，如果你可以提交一个pytorch或者onnx的支持的PR，那就太好了
