### ISSUE TITLE
请问在这行代码中的expf()是在哪个头文件包含的呢？

### ISSUE THREAD

**Issue by XDUWQ** [zjhellofss/KuiperInfer#25]
https://github.com/zjhellofss/KuiperInfer/blob/1b97b9f2a60ef96a877b7b52ad42a0669eb548bb/source/layer/details/sigmoid.cpp#L38  
请问在这行代码中的 `expf` 是在哪个头文件包含的呢？

是<math.h>中的吗：https://www.enseignement.polytechnique.fr/informatique/INF478/docs/Cpp/en/c/numeric/math/exp.html 
但是我看 `sigmoid.cpp/sigmoid.hpp` 中并没有 `#include <math.h>`呀。

跪求大佬解答

**Comment by zjhellofss** [comment]
应该是隐式包含的，armadillo头文件中就包含了cmath

**Comment by XDUWQ** [comment]
> 应该是隐式包含的，armadillo头文件中就包含了cmath

明白了，谢谢大佬解答！
