### ISSUE TITLE
求大佬解释一下这里为什么要先定义一个`Operator`空类呢？

### ISSUE THREAD

**Issue by XDUWQ** [zjhellofss/KuiperInfer#26]
![image](https://user-images.githubusercontent.com/37444407/232958191-236caf44-a6f9-43b0-a35e-76116d029f08.png)
 https://github.com/zjhellofss/KuiperInfer/blob/1b97b9f2a60ef96a877b7b52ad42a0669eb548bb/include/runtime/ir.h#L170
这里为什么先声明了一下`Operator`类这个空类，然后下面再具体定义呢？
是为了先在`Operand`类中使用吗？但是在`Operand`类中使用的时候`Operator`还是个空类没有被定义过吧？
没想明白这样做的目的是什么？
跪求大佬解答！

**Comment by zjhellofss** [comment]
这是一个声明，因为operand类中有operator指针类型。如果单使用一个指针，不需要引入头文件，前向声明一下就可以

**Comment by zjhellofss** [comment]
你加一下交流群吧，readme里有二维码，这样问答起来方便。

**Comment by XDUWQ** [comment]
好的，谢谢大佬解答～
