### ISSUE TITLE
关于Tensor的疑问

### ISSUE THREAD

**Issue by Postroggy** [zjhellofss/KuiperInfer#31]
为什么定义Tensor类的时候，使用的是`Armadillo`库，而不是比较流行 且 速度比较快的 `Eigen`矩阵库呢？性能方面`Armadillo`比`Eigen`差的挺多的。

**Comment by zjhellofss** [comment]
1. armadillo虽然默认实现慢，但是它也可以链接openblas或intel-mkl的，用这两者的实现，这样速度就非常快了。
2. arma虽然冷门，但是我对它更加熟悉，接口和matlab也比较相似，同学上手也很快。
3. 确实有同学在学习之后用Eigen做了一个复刻版，[https://github.com/zpye/SimpleInfer](https://github.com/zpye/SimpleInfer)
