### ISSUE TITLE
实现对yolov8的支持

### ISSUE THREAD

**Issue by morandave** [zjhellofss/KuiperInfer#55]
我尝试使KuiperInfer支持yolov8，在将转换后的PNNX格式的模型文件导入时遇到问题，在读取bin文件时总是报错，在尝试获取某个filename的size时无法获得正确的大小，返回-1，（猜测是模型转换时发生错误导致bin文件不正确）请问有什么办法确定bin文件是否正确，或者有好用的模型格式转换方法吗，

**Comment by morandave** [comment]
甚至我又尝试了一遍resnet18，将其从torchscript转换为pnnx.bin和pnnx.param后依旧无法正确读取

**Comment by zjhellofss** [comment]
你可以把模型文件提供给我 resnet18的，也就是你说的无法加载的pnnx.param和pnnx.bin

**Comment by zjhellofss** [comment]
> 甚至我又尝试了一遍resnet18，将其从torchscript转换为pnnx.bin和pnnx.param后依旧无法正确读取

1

**Comment by morandave** [comment]
已经解决了，之前使用的是最新版本的PNNX转换工具，转换出的bin文件格式似乎与以前版本有所不同，导致store_zip.cpp读取bin文件时会出错，在使用了PNNX的20230217版本转换模型后可以成功读取

**Comment by zjhellofss** [comment]
> 已经解决了，之前使用的是最新版本的PNNX转换工具，转换出的bin文件格式似乎与以前版本有所不同，导致store_zip.cpp读取bin文件时会出错，在使用了PNNX的20230217版本转换模型后可以成功读取

可以的，您提供的信息对我们非常有用，谢谢
