### ISSUE TITLE
 可否在项目中提供一个开发环境Dockerfile 或 镜像 ？

### ISSUE THREAD

**Issue by lvsoso** [zjhellofss/KuiperInfer#7]
提供一个开发环境 Dockerfile 可以方便大家快速把框架跑起来，节省搭建环境的时间。

**Comment by zjhellofss** [comment]
这两天找时间会做这个事情

**Comment by zjhellofss** [comment]
> 提供一个开发环境 Dockerfile 可以方便大家快速把框架跑起来，节省搭建环境的时间。

同学，你好！你看一下readme，我已经更新了一个镜像上去。 阿里云的，应该速度上都没问题。

**Comment by lvsoso** [comment]
> > 提供一个开发环境 Dockerfile 可以方便大家快速把框架跑起来，节省搭建环境的时间。
> 
> 同学，你好！你看一下readme，我已经更新了一个镜像上去。 阿里云的，应该速度上都没问题。

非常感谢！

另外，提个小小的建议：代码可以克隆到本地，然后通过 -v 的方式挂载进行进去，这样镜像体积也不会很大；

当然这个建议也可以忽略掉，及时提供镜像已经足够了   ：）

**Comment by zjhellofss** [comment]
> 

这点我再研究学习一下，因为我对docker也不是很熟练，提供镜像这个操作还是我临时学的。
