### ISSUE TITLE
const cv::Mat &split_image_t = split_image.t();貌似不需要转置吧

### ISSUE THREAD

**Issue by hyaihjq** [zjhellofss/KuiperInfer#9]
https://github.com/zjhellofss/KuiperInfer/blob/dd598cd543c16ee59b4c1b71bbc1352270894bfa/demos/main.cpp#L56

**Comment by zjhellofss** [comment]
armadillo和cv::mat里面的数据一个是行主序，一个是列主序。
opencv中有图像为 
1 2 3
4 5 6
7 8 9 
直接用memcpy拷贝到arma中的话就是
1 4  7 
2 5  8
3 6  9
所以需要先tranpose一下。

**Comment by hyaihjq** [comment]
> armadillo和cv::mat里面的数据一个是行主序，一个是列主序。 opencv中有图像为 1 2 3 4 5 6 7 8 9 直接用memcpy拷贝到arma中的话就是 1 4 7 2 5 8 3 6 9 所以需要先tranpose一下。

感谢回复
